### ISSUE TITLE
Getting 403 Forbidden Error

### ISSUE THREAD

**Issue by msumeet** [jugend/amazon-ecs#47]
Hi,
I am getting 403 Forbidden error. Pls check.

**Comment by kyletcarlson** [comment]
I am too. Ruby 2.1.2 if that matters.

**Comment by ryuzee** [comment]
@msumeet @kyletcarlson 

I also encountered the same issue and have just resolved it.
Amazon's product advertising API now requires AWS account. 

- If you do not have AWS Account, create it here ( https://console.aws.amazon.com )
- Login to AWS and go to IAM setting page
- In IAM section, create IAM user and its access key and secret key
- Set them as environment variables
