### ISSUE TITLE
PA-API 5.0

### ISSUE THREAD

**Issue by hase1031** [jugend/amazon-ecs#70]
Amazon has released PA-API 5.0.
We must use the new API because amazon will shutdown the old API at Nov 30th, 2019.
https://webservices.amazon.com/paapi5/documentation/migration-guide/whats-new-in-paapi5.html

Can you have any upgrade plan?

**Comment by dkam** [comment]
Hey, I've started a [gem](https://github.com/dkam/paapi) for v5 and the [Vacuum](https://github.com/hakanensari/vacuum) gem is in the process of being updated.

**Comment by hase1031** [comment]
@dkam Thank you. I close this issue.
